import React from "react";
import Head from "next/head";

import PageWrapper from "../components/PageWrapper";
import List from "../components/List";

function HotelList() {
  return (
    <PageWrapper>
      <Head>
        <title> Booking.com | Search Hotels </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <List />
      <style jsx> {``} </style>
    </PageWrapper>
  );
}

export default HotelList;
