import React from "react";
import Head from "next/head";
import Navbar from "./../components/Navbar";
import Header from "./../components/Header";
import MailList from "./../components/MailList";
import Footer from "./../components/Footer";

import PageWrapper from "../components/PageWrapper";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import {
  faCircleArrowLeft,
  faCircleArrowRight,
  faCircleXmark,
  faLocationDot,
} from "@fortawesome/free-solid-svg-icons";

const photos = [
  "https://t-cf.bstatic.com/xdata/images/hotel/max1024x768/153575650.jpg?k=fd3d444eac9087982919f3a2b6cda7b4539dcd1c0ff0e2a1aa6ef2f6b9552c23&o=&hp=1",
  "https://t-cf.bstatic.com/xdata/images/hotel/max1024x768/153585297.jpg?k=f0f0f7dbf89b2bdc4cf6ec35fe469ea4f3247c1c0f3f736165c4ff269d348711&o=&hp=1",
  "https://t-cf.bstatic.com/xdata/images/hotel/max1024x768/178941396.jpg?k=d03f975405e3a5932903178df3c7f72f46eecacdd81fca5432a5770aa6d0b949&o=&hp=1",
  "https://t-cf.bstatic.com/xdata/images/hotel/max1024x768/153589014.jpg?k=2734f8a71d18ce9c903efc545fa21aee31a2715229dcfe5dff783482268d27ad&o=&hp=1",
  "https://t-cf.bstatic.com/xdata/images/hotel/max1024x768/153591979.jpg?k=f370f5781b828ea71f16ab8c98361d8551eff591f866f1f1e83e8beb0e699657&o=&hp=1",
  "https://t-cf.bstatic.com/xdata/images/hotel/max1024x768/153585300.jpg?k=75c96c172fb79474f59bdeaa4f10c2f9158e3d4685e8449db856bf4c4cb5d891&o=&hp=1",
];

function Hotel() {
  const [slideNumber, setSlideNumber] = React.useState(0);
  const [open, setOpen] = React.useState(false);

  const handleOpen = (i) => {
    setSlideNumber(i);
    setOpen(true);
  };

  const handleArrow = (detector) => {
    if (detector === "i") {
      if (slideNumber === photos.length - 1) {
        return;
      } else {
        setSlideNumber(slideNumber + 1);
      }
    } else {
      if (slideNumber === 0) {
        return;
      } else {
        setSlideNumber(slideNumber - 1);
      }
    }
  };
  return (
    <PageWrapper>
      <Head>
        <title> Booking.com | Hotel </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {open && (
        <div className="slider">
          <button className="close" onClick={() => setOpen(false)}>
            <FontAwesomeIcon icon={faCircleXmark} color="white" />
          </button>
          <button className="arrow a-left" onClick={() => handleArrow("d")}>
            <FontAwesomeIcon icon={faCircleArrowLeft} color="white" />
          </button>

          <div className="sliderWrapper">
            <img
              src={photos[slideNumber]}
              alt="hotel image"
              className="sliderImg"
            />
          </div>
          <button className="arrow a-right" onClick={() => handleArrow("i")}>
            <FontAwesomeIcon icon={faCircleArrowRight} color="white" />
          </button>
        </div>
      )}
      <Navbar />
      <Header type="list" />
      <div className="hotelContainer">
        <div className="hotelWrapper">
          <button className="bookNow">Reserve or Book Now!</button>
          <h1 className="hotelTitle">Majestic Hotel</h1>
          <div className="hotelAddress">
            <FontAwesomeIcon icon={faLocationDot} />
            <span>Elton St 120 NY</span>
          </div>
          <span className="hotelDistance">
            Excellent location - 500m from center
          </span>
          <span className="hotelPriceHighlight">
            Book a stay over $114 at this property and get a fee airport taxi
          </span>
          <div className="hotelImages">
            {photos.map((photo, i) => {
              return (
                <div className="hotelImgWrapper" key={i}>
                  <img
                    src={photo}
                    onClick={() => handleOpen(i)}
                    className="hotelImg"
                  />
                </div>
              );
            })}
          </div>
          <div className="hotelDetails">
            <div className="hotelDetailsTexts">
              <h1 className="hotelTitle"> Stay in the heart of krakov</h1>
              <p className="hotelDesc">
                Set 3.1 mi from Forum Mall, Koramangala, Mistyblue Serviced
                Apartments is a fully furnished serviced apartments on
                Bannerghatta Road. The property offers a terrace, and
                accommodations with free WiFi, elevator and power backup.
                Air-conditioned rooms come with a flat-screen TV, a kitchen with
                a dining area, a huge living room, two balconies and a private
                bathroom. A dishwasher and kettle are also provided.
                Housekeeping and laundry service is available. A local breakfast
                is served each morning at the property. ISKCON Hare Krishna
                Temple is 3.7 mi from the aparthotel, while Bull Temple is 3.7
                mi from the property. The nearest airport is Kempegowda
                International Airport, 22 mi from Mistyblue Serviced Apartments.
                Families in particular like the location – they rated it 8.7 for
                a stay with kids.
              </p>
            </div>
            <div className="hotelDetailsPrice">
              <h1>Perfect for 2 days stay!</h1>
              <span>
                Mistyblue Serviced Apartments has been welcoming Booking.com
                guests since Aug 3, 2018
              </span>
              <h2>
                <b>$945</b> (9 nights)
              </h2>
              <button>Reserve or Book Now</button>
            </div>
          </div>
        </div>
        <MailList />
        <Footer />
      </div>

      <style jsx>{`
        .hotelContainer {
          display: flex;
          align-items: center;
          flex-direction: column;
          margin-top: 20px;
          //border: 10px dashed black;
          gap: 30px;
        }

        .hotelWrapper {
          width: 100%;
          max-width: 1024px;
          display: flex;
          flex-direction: column;
          gap: 10px;
          position: relative;
        }

        .bookNow {
          position: absolute;
          top: 10px;
          right: 0;
          border: none;
          padding: 10px 20px;
          outline: none;
          color: white;
          background: #0071c2;
          font-weight: 600;
          border-radius: 5px;
        }

        .hotelTitle {
          font-size: 1.5rem;
        }

        .hotelAddress {
          font-size: 0.75rem;
          display: flex;
          align-items: center;
          gap: 10px;
        }

        .hotelDistance {
          color: #0071c2;
          font-weight: 500;
        }

        .hotelPriceHighlight {
          color: #008009;
          font-weight: 500;
        }

        .hotelImages {
          display: flex;
          flex-wrap: wrap;
          justify-content: space-between;
        }

        .hotelImgWrapper {
          width: 33%;
          min-height: 300px;
          height: 300px;
          //border: 1px solid green;
          overflow: hidden;
          cursor: pointer;
        }

        .hotelImg {
          width: 100%;
          height: 100%;
          object-fit: cover;
          transition: all 350ms ease;
        }

        .hotelImg:hover {
          transform: scale(1.05);
        }

        .hotelDetails {
          display: flex;
          justify-content: space-between;
          gap: 20px;
          margin-top: 20px;
        }

        .hotelDetailsTexts {
          flex: 3;
        }

        .hotelDetailsPrice {
          flex: 1;
          background: #ebf3ff;
          padding: 20px;
          display: flex;
          flex-direction: column;
          gap: 20px;
        }

        .hotelDetailsPrice > h1 {
          font-size: 1.125rem;
          color: #555;
        }

        .hotelDetailsPrice > span {
          font-size: 0.875rem;
        }

        .hotelDetailsPrice > h2 {
          font-weight: 300;
        }

        .hotelDetailsPrice > button {
          border: none;
          outline: none;
          padding: 10px 20px;
          background: #0071c2;
          color: white;
          font-weight: bold;
          border-radius: 5px;
        }

        .hotelDesc {
          font-size: 0.875rem;
          margin-top: 20px;
        }

        .slider {
          position: sticky;
          top: 0;
          left: 0;
          width: 100vw;
          height: 100vh;
          z-index: 99;
          background: black;
          display: flex;
          align-items: center;
          -webkit-tap-highlight-color: transparent;
          // pointer-events: none;
          outline: none;
          user-select: none;
        }

        .sliderWrapper {
          width: 100%;
          height: 100%;
          display: flex;
          justify-content: center;
          align-items: center;
          position: relative;
          //border: 10px dashed white;
          -webkit-tap-highlight-color: transparent;

          outline: none;
          user-select: none;
          -moz-user-select: none;
          -webkit-user-select: none;
          -ms-user-select: none;
        }

        .sliderImg {
          width: 80%;
          height: 80vh;
          object-fit: cover;
          -webkit-tap-highlight-color: transparent;

          outline: none;
        }

        .close {
          font-size: 1.875rem;
          position: absolute;
          top: 20px;
          right: 40px;
          z-index: 9999999;
          -webkit-tap-highlight-color: transparent;

          outline: none;
          background: none;
          border: none;
        }

        .arrow {
          font-size: 1.875rem;
          z-index: 9999999;
          -webkit-tap-highlight-color: transparent;

          border: 3px solid white;
          outline: none;
          background: none;
          border: none;
        }

        .a-left {
          position: absolute;
          top: calc(50% - 15px);
          left: 60px;
          -webkit-tap-highlight-color: transparent;
          outline: none;
        }

        .a-right {
          position: absolute;
          top: calc(50% - 15px);
          right: 60px;
          -webkit-tap-highlight-color: transparent;
          outline: none;
        }
      `}</style>
    </PageWrapper>
  );
}

export default Hotel;
