import Head from "next/head";
import Featured from "../components/Featured";
import FeaturedProperties from "../components/FeaturedProperties";
import Footer from "../components/Footer";
import Header from "../components/Header";
import MailList from "../components/MailList";
import Navbar from "../components/Navbar";
import PropertyList from "../components/PropertyList";
import PageWrapper from "../components/PageWrapper";

export default function Home() {
  return (
    <PageWrapper>
      <Head>
        <title>Booking.com | Official site</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />

        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <Header />
      <div className="homeContainer">
        <Featured />
        <h1 className="homeTitle">Browse property by type</h1>
        <PropertyList />
        <h1 className="homeTitle">Homes guests love</h1>
        <FeaturedProperties />
        <MailList />
        <Footer />
      </div>

      <style jsx>
        {`
           {
            /* .mainWrapper {
            min-width: 100%;
            width: 100%;
            min-height: 100vh;
            //border: 4px dashed blue;
          } */
          }

          .homeContainer {
            margin-top: 150px;
            display: flex;
            flex-direction: column;
            align-items: center;
            gap: 30px;
          }

          .homeTitle {
            width: 100%;
            //width: 1024px;
            font-size: 1.15rem;
            padding: 0px 12px;
          }

          @media only screen and (min-width: 768px) {
            .homeContainer {
              margin-top: 80px;
            }

            .homeTitle {
              font-size: 1.5rem;
            }
          }

          @media only screen and (min-width: 1024px) {
            .homeTitle {
              max-width: 1024px;
              padding: 0px;
            }
          }
        `}
      </style>
    </PageWrapper>
  );
}
