import Head from "next/head";
import Image from "next/image";
import Featured from "../components/Featured";
import FeaturedProperties from "../components/FeaturedProperties";
import Header from "../components/Header";
import MailList from "../components/MailList";
import Navbar from "../components/Navbar";
import PropertyList from "../components/PropertyList";

export default function Home() {
  return (
    <>
      <div>
        <Head>
          <title>Booking.com | Official site</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Navbar />
        <Header />
        <div className="homeContainer">
          <Featured />
          <h1 className="homeTitle">Browse property by type</h1>
          <PropertyList />
          <h1 className="homeTitle">Homes guests love</h1>
          <FeaturedProperties />
          <MailList />
        </div>
      </div>
      <style jsx>
        {`
          .homeContainer {
            margin-top: 50px;
            display: flex;
            flex-direction: column;
            align-items: center;
            gap: 30px;
          }

          .homeTitle {
            width: 1024px;
            font-size: 1.5rem;
          }
        `}
      </style>
    </>
  );
}
